# Generated by Django 5.0.1 on 2024-03-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction_listing",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
