# Generated by Django 5.0.1 on 2024-06-13 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0003_alter_auction_listing_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auction_listing",
            name="least_bid",
        ),
        migrations.AddField(
            model_name="auction_listing",
            name="starting_bid",
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name="bids",
            name="auction_listing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bids",
                to="auctions.auction_listing",
            ),
        ),
    ]
