# Generated by Django 5.0.1 on 2024-06-13 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0004_remove_auction_listing_least_bid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auction_listing",
            name="starting_bid",
        ),
        migrations.RemoveField(
            model_name="bids",
            name="auction_listing",
        ),
        migrations.AddField(
            model_name="auction_listing",
            name="least_bid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="price",
                to="auctions.bids",
            ),
        ),
    ]
